---
- hosts: clients
  gather_facts: no
  vars:
   - left_hostname: "left.pod0.wscc.cloud"
   - right_hostname: "right.pod0.wscc.cloud"
#  connection: local
  tasks:
  - name: Set 192.168.200.2 gi2 Right
    ios_config:
     parents: "interface gi2"
     lines:
       - ip address 192.168.200.2 255.255.255.0
       - no shut
    when: inventory_hostname == "Right"

  - name: Set 192.168.100.2 gi2 Left
    ios_config:
     parents: "interface gi2"
     lines:
       - ip address 192.168.100.2 255.255.255.0
       - no shut
    when: inventory_hostname == "Left"

  - name: GRE int tun1 Left
    ios_config:
     parents: "interface tun1"
     lines:
       - ip address 200.100.100.1 255.255.255.252
       - no shut
       - tunnel source gi1
       - tunnel mode gre ip
       - 'tunnel destination {{ right_hostname }}'
    when: inventory_hostname == "Left"

  - name: GRE int tun1 Right
    ios_config:
     parents: "interface tun1"
     lines:
       - ip address 200.100.100.2 255.255.255.252
       - no shut
       - tunnel source gi1
       - tunnel mode gre ip
       - 'tunnel destination {{ left_hostname }}'
    when: inventory_hostname == "Right"

  - name: ip route 192.168.200.0/24 Left
    ios_config:
     lines:
       - ip route 192.168.200.0 255.255.255.0 200.100.100.2
    when: inventory_hostname == "Left"

  - name: ip route 192.168.100.0/24 Right
    ios_config:
     lines:
       - ip route 192.168.100.0 255.255.255.0 200.100.100.1
    when: inventory_hostname == "Right"

  - name: isakmp policy
    ios_config:
     parents: "crypto isakmp policy 1"
     lines:
       - encr aes
       - hash sha256
       - authentication pre-share
       - group 14

  - name: ipsec key
    ios_config:
     lines:
       - crypto isakmp key cisco address 0.0.0.0

  - name: ipsec trasform-set
    ios_config:
     parents: "crypto ipsec transform-set TS esp-aes esp-md5-hmac"
     lines:
       - mode transport

  - name: ipsec profile
    ios_config:
     parents: "crypto ipsec profile vpn"
     lines:
       - set transform-set TS

  - name: set ipsec on GRE
    ios_config:
     parents: "int tun1"
     lines:
       - tunnel protection ipsec profile vpn


  - name: access-list NAT Left
    ios_config:
     parents: "ip access-list standard NAT"
     lines:
       - permit 192.168.100.0 0.0.0.255
    when: inventory_hostname == "Left"


  - name: access-list NAT Right
    ios_config:
     parents: "ip access-list standard NAT"
     lines:
       - permit 192.168.200.0 0.0.0.255
    when: inventory_hostname == "Right"

  - name: nat inside
    ios_config:
     parents: "int gi2"
     lines:
       - ip nat inside

  - name: nat outside
    ios_config:
     parents: "int gi1"
     lines:
       - ip nat outside

  - name: nat overload
    ios_config:
     lines:
       - ip nat inside source list NAT interface gi1 overload

  - name: outside_ip_right
    ios_command:
      commands: show ip int br gi1
    register: right_out
    when: inventory_hostname == "Right"

  - name: show_outside_ip_right
    debug:
      var: "{{ right_out.stdout[0].split('\n')[1].split()[1] }}"
    when: inventory_hostname == "Right"

  - name: outside_ip_left
    ios_command:
      commands: show ip int br gi1
    register: left_out
    when: inventory_hostname == "Left"

  - name: show_outside_ip_left
    debug:
      var: "{{ left_out.stdout[0].split('\n')[1].split()[1] }}"
    when: inventory_hostname == "Left"

  - name: left_static_nat_ssh_100.20_and_udp1333
    ios_config:
     lines:
       - "ip nat inside source static tcp 192.168.100.20 22 {{ left_out.stdout[0].split('\n')[1].split()[1] }} 1022"
       - "ip nat inside source static udp 192.168.100.20 1333 {{ left_out.stdout[0].split('\n')[1].split()[1] }} 1333"
    when: inventory_hostname == "Left"

  - name: right_static_nat_ssh_200.20_and_udp1333
    ios_config:
     lines:
       - "ip nat inside source static tcp 192.168.200.20 22 {{ right_out.stdout[0].split('\n')[1].split()[1] }} 1022"
       - "ip nat inside source static udp 192.168.200.20 1333 {{ right_out.stdout[0].split('\n')[1].split()[1] }} 1333"
    when: inventory_hostname == "Right"
